[ping_probe]
python.version = python3
python.required = 3.13
count = 4
timeout_ms = 2000
interval = 60
index = default

[speedtest_probe]
python.version = python3
python.required = 3.13
profile = standard
download_mb = 25
upload_mb = 5
interval = 1800
index = default

[netkit_tls_probe]
python.version = python3
python.required = 3.13
timeout_ms = 5000
interval = 3600
index = default
