[netkit:ping]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
DATETIME_CONFIG = NONE
TRUNCATE = 10000
category = Splunk App/Add-on

[netkit:speedtest]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
DATETIME_CONFIG = NONE
TRUNCATE = 10000
category = Splunk App/Add-on

[source::.../var/log/splunk/TA_netkit_*.log]
sourcetype = netkit_log

[netkit_log]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 10000
TIME_FORMAT = %Y-%m-%d %H:%M:%S,%3N
TIME_PREFIX = ^
MAX_TIMESTAMP_LOOKAHEAD = 25
category = Splunk App/Add-on
