[admin:TA_netkit_configuration]
match = /
members = TA_netkit_settings

[admin:TA_netkit_inputs]
match = /
members = TA_netkit_ping_probe, TA_netkit_speedtest_probe

[admin_external:TA_netkit_settings]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA_netkit_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:TA_netkit_ping_probe]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA_netkit_rh_ping_probe.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:TA_netkit_speedtest_probe]
handlertype = python
python.version = python3
python.required = 3.13
handlerfile = TA_netkit_rh_speedtest_probe.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
