[expose:TA_netkit_settings]
pattern = TA_netkit_settings
methods = POST, GET

[expose:TA_netkit_settings_specified]
pattern = TA_netkit_settings/*
methods = POST, GET, DELETE

[expose:TA_netkit_ping_probe]
pattern = TA_netkit_ping_probe
methods = POST, GET

[expose:TA_netkit_ping_probe_specified]
pattern = TA_netkit_ping_probe/*
methods = POST, GET, DELETE

[expose:TA_netkit_speedtest_probe]
pattern = TA_netkit_speedtest_probe
methods = POST, GET

[expose:TA_netkit_speedtest_probe_specified]
pattern = TA_netkit_speedtest_probe/*
methods = POST, GET, DELETE

[expose:data/indexes]
pattern = data/indexes
methods = GET
